EXEC sp_MSForEachTable 'DISABLE TRIGGER ALL ON ?'
EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'
EXEC sp_MSForEachTable 'DELETE FROM ?'
EXEC sp_MSForEachTable 'ALTER TABLE ? CHECK CONSTRAINT ALL'
EXEC sp_MSForEachTable 'ENABLE TRIGGER ALL ON ?'
DBCC CHECKIDENT ('users', RESEED, -1)
DBCC CHECKIDENT ('user_info', RESEED, -1)
DBCC CHECKIDENT ('employee_info', RESEED, -1)
DBCC CHECKIDENT ('epochs', RESEED, -1)
DBCC CHECKIDENT ('data', RESEED, -1)
DBCC CHECKIDENT ('data_info', RESEED, -1)
